'''
Hey there! This is Lab 8 for CSCI 161 Summer 2021
Tests a class object that acts as a queue with 
additional priority functionality allowing the addition
of items to the queue based on this priority reference.
By Kevin Jordan kevin.jordan@und.edu 1301006 (and Tom Stokke UND)
'''

from PriorityQueue import *

print("Testing of the new fancy queue thingy")
print()
print("Creating class with max 3 items")
q = PriorityQueue(3)
print("Adding 'a' to queue with no priority (default = 1)")
q.enqueue('a')
print("Adding 'b' to queue with no priority (default = 1)")
q.enqueue('b')
print("Adding 'c' to queue with no priority (default = 1)")
q.enqueue('c')
print()
print("If we dequeue all, should return 'a', 'b', 'c'")
print("as all have same priority and this was order added")
print("Lets try it")
print()
print(q.dequeue())
print(q.dequeue())
print(q.dequeue())
print("Success!")
print()
print("Ok, so lets try if we give a different priority")
print("Adding 'a' to queue with priority 1")
q.enqueue('a', 1)
print("Adding 'b' to queue with priority 2")
q.enqueue('b', 2)
print("Adding 'c' to queue with priority 3")
q.enqueue('c', 3)
print()
print("If we dequeue all, should return 'c', 'b', 'a'")
print("as 'c' has highest, 'b' middle, and 'a' lowest priority")
print("Lets try it")
print()
print(q.dequeue())
print(q.dequeue())
print(q.dequeue())
print("Success!")
print()
print("Ok, so lets try if we give another different priority")
print("Adding 'a' to queue with priority 2")
q.enqueue('a', 2)
print("Adding 'b' to queue with priority 3")
q.enqueue('b', 3)
print("Adding 'c' to queue with priority 2")
q.enqueue('c', 2)
print()
print("If we dequeue all, should return 'b', 'a', 'c'")
print("as 'b' has highest priority, and 'a' was added")
print("before 'c' which both have the same priority")
print("Lets try it")
print()
print(q.dequeue())
print(q.dequeue())
print(q.dequeue())
print("Success!")
print()
print("And so completes a demo of the nifty little queue thingy")