'''
Hey there! This is Lab 9 for CSCI 161 Summer 2021
Tests a class object that creates a fixed length linked list.
Essentially the same as Lab 6b but with additional tests of getNextItem
as the previous Lab 6 did not include mods to this and so was not tested.
Includes numerous methods such as add, remove, size, 
overallCount, count, isInList, isFull, isEmpty, reset, getNextItem.
Uses the inner class structure to keep count of same values.
By Kevin Jordan kevin.jordan@und.edu 1301006 (and Tom Stokke UND)
'''

from UnsortedCountListLL import *

print("Lets initialize our list to max 3 items")
u = UnsortedCountListLL(3)
print("Lets add an 'a'. Did it add?")
print(u.add('a'))
print("Lets add an 'a'. Did it add?")
print(u.add('a'))
print("So 'a' is in the list right?")
print(u.isInList('a'))
print("How many counts of 'a' are there?")
print(u.count('a'))
print("Lets add a 'b'. Did it add?")
print(u.add('b'))
print("Lets add a 'b'. Did it add?")
print(u.add('b'))
print("Lets add a 'b'. Did it add?")
print(u.add('b'))
print("How many counts of 'b' are there?")
print(u.count('b'))
print("Lets add a 'c'. Did it add?")
print(u.add('c'))
print("Lets add a 'd'. Did it add?")
print(u.add('d'))
print("I guess the list is full")
print("So 'c' is in the list right?")
print(u.isInList('c'))
print("Well how many times is 'x' in the list?")
print(u.count('x'))
print("Ok, how many unique items do we have now? I forget!")
print(u.size())
print("I feel like we added more items...")
print("What is the total count of everything added?")
print(u.overallCount())
print("What is current item?")
print(u.getNextItem())
print("What is next item?")
print(u.getNextItem())
print("What is next item?")
print(u.getNextItem())
print("What is next item?")
print(u.getNextItem())
print("Ok, can we remove an 'x'?")
print(u.remove('x'))
print("Hmm, remove an 'a' then. Did it work?")
print(u.remove('a'))
print("Ok, how many 'a' left?")
print(u.count('a'))
print("Ok, remove an 'a' again. Did it work?")
print(u.remove('a'))
print("Ok, how many 'a' left?")
print(u.count('a'))
print("Ok, how many 'b' left?")
print(u.count('b'))
print("What is the total count of everything in the list?")
print(u.overallCount())
print("How many unique items left?")
print(u.size())
print("Kewllll. Later skater!")